### ISSUE TITLE
MemGPT Python Client Tracker 

### ISSUE THREAD

**Issue by sarahwooders** [cpacker/MemGPT#1042]
We are adding functionality to the MemGPT python client to match commands implemented in the REST API. This tracks progress towards matching functionality of the REST API with the clients. 

## `Admin` Client 

- [x] Get all users #1157
- [x] Create user #1033 
- [x] Delete user #1033 
- [x] Create new API key #1157
- [x] Get API keys #1157
- [x] Delete API key #1157

## `RESTClient` User Client 

Agents 
- [x] Run command #1160
- [x] Get agent config #1160
- [x] Update agent name #1160
- [x] Delete agent #1033 
- [x] List agents #1160
- [x] Create agent #1033 
- [x] Get agent memory #1160
- [x] Update agent memory #1160
- [x] Get agent messages #1160
- [x] Send message #1033 

Humans

- [x] List humans #1160
 
Personas 

- [x] List personas #1160

Models 

- [x] List models #1160

Config 

- [x] Get server config #1160

## `LocalClient` User Client 

Agents 
- [ ] Run command 
- [ ] Get agent config 
- [ ] Update agent name 
- [x] Delete agent #1033 
- [ ] List agents
- [x] Create agent #1033 
- [x] Get agent memory 
- [ ] Update agent memory 
- [ ] Get agent messages
- [x] Send message #1033 

Humans

- [ ] List humans 

Personas 

- [ ] List personas

Models 

- [ ] List models 

Config 

- [ ] Get server config
