### ISSUE TITLE
Improve the CLI

### ISSUE THREAD

**Issue by vivi** [cpacker/MemGPT#11]
- [x] probably move to questionary
- [x] ask if want to update embeddings / `--refresh-embeddings` flag
- [x] support #8 
- [x] currently, CLI only supports a limited amount of characters for input. 

~- [ ] questionary-style CLI UI for (1) loading+saving (2) viewing bot memory~

**Comment by drnic** [comment]
I started having a conversation about some code. But when I pasted a chunk of code into the CLI, the cli only took the first line -- which led to a nonsensical conversation. Perhaps could we support toggling between single line + multiline inputs (like chatgpt UI)

**Comment by vivi** [comment]
@drnic Did you try typing `//` to enter multi-line mode?

**Comment by drnic** [comment]
@vivi I hadn't and that's embarrassing :) I've now found https://github.com/cpacker/MemGPT#interactive-cli-commands section of bonus commands :)
