### ISSUE TITLE
Store MemGPT config and agent configs via storage connector API 

### ISSUE THREAD

**Issue by sarahwooders** [cpacker/MemGPT#768]
#708 migrates loaded data, archival memory, and recall memory into storage connectors. 

We will also migrate agent and user metadata (similar to source metadata) into storage connectors so everything can be stored in a DB. 

## Todos
- [ ] Create metadata tables: 
  - [ ] `Agents` - Store created agents and attached data sources 
  - [ ] `Users` - Store user configs 
- [ ] Add deletion support for agents

**Comment by sarahwooders** [comment]
Closed by #708
